[2025-10-27T13:49:27.850+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-27T13:49:27.864+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_pipeline.extract manual__2025-10-27T13:49:27.421911+00:00 [queued]>
[2025-10-27T13:49:27.869+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_pipeline.extract manual__2025-10-27T13:49:27.421911+00:00 [queued]>
[2025-10-27T13:49:27.871+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-27T13:49:27.879+0000] {taskinstance.py:2330} INFO - Executing <Task(KubernetesPodOperator): extract> on 2025-10-27 13:49:27.421911+00:00
[2025-10-27T13:49:27.885+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=748) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-27T13:49:27.885+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_pipeline', 'extract', 'manual__2025-10-27T13:49:27.421911+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_pipeline_dag.py', '--cfg-path', '/tmp/tmpqo83eo74']
[2025-10-27T13:49:27.887+0000] {standard_task_runner.py:64} INFO - Started process 751 to run task
[2025-10-27T13:49:27.887+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask extract
[2025-10-27T13:49:27.932+0000] {task_command.py:426} INFO - Running <TaskInstance: ecommerce_pipeline.extract manual__2025-10-27T13:49:27.421911+00:00 [running]> on host 74a766c7185d
[2025-10-27T13:49:28.013+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T13:49:27.421911+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T13:49:27.421911+00:00'
[2025-10-27T13:49:28.015+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-27T13:49:28.058+0000] {pod.py:1121} INFO - Building pod extract-jyowhq59 with labels: {'dag_id': 'ecommerce_pipeline', 'task_id': 'extract', 'run_id': 'manual__2025-10-27T134927.4219110000-23d24b64a', 'kubernetes_pod_operator': 'True', 'try_number': '1'}
[2025-10-27T13:49:28.066+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-27T13:49:28.067+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 591, in execute
    return self.execute_sync(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 599, in execute_sync
    self.pod_request_obj = self.build_pod_request_obj(context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 1130, in build_pod_request_obj
    "airflow_kpo_in_cluster": str(self.hook.is_in_cluster),
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 283, in is_in_cluster
    self.api_client  # so we can determine if we are in_cluster or not
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 291, in api_client
    return self.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 239, in get_conn
    config.load_kube_config(
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 815, in load_kube_config
    loader = _get_kube_config_loader(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 772, in _get_kube_config_loader
    raise ConfigException(
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.
[2025-10-27T13:49:28.079+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ecommerce_pipeline, task_id=extract, run_id=manual__2025-10-27T13:49:27.421911+00:00, execution_date=20251027T134927, start_date=20251027T134927, end_date=20251027T134928
[2025-10-27T13:49:28.087+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task extract (Invalid kube-config file. No configuration found.; 751)
[2025-10-27T13:49:28.107+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-27T13:49:28.122+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-27T13:49:28.125+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
